# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threshold_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Threshold3DialogBase(object):
    def setupUi(self, Threshold3DialogBase):
        Threshold3DialogBase.setObjectName("Threshold3DialogBase")
        Threshold3DialogBase.resize(619, 830)
        self.gridLayout_5 = QtWidgets.QGridLayout(Threshold3DialogBase)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header = QtWidgets.QLabel(Threshold3DialogBase)
        self.header.setText("")
        self.header.setTextFormat(QtCore.Qt.PlainText)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout_5.addWidget(self.header)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.threshold_0_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_0_label.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_0_label.setObjectName("threshold_0_label")
        self.horizontalLayout.addWidget(self.threshold_0_label)
        self.threshold_0_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.threshold_0_slider.setMaximumSize(QtCore.QSize(390, 21))
        self.threshold_0_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_0_slider.setObjectName("threshold_0_slider")
        self.horizontalLayout.addWidget(self.threshold_0_slider)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(Threshold3DialogBase)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.horizontalLayout.addWidget(self.doubleSpinBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.threshold_0_color_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_0_color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_0_color_label.setObjectName("threshold_0_color_label")
        self.horizontalLayout_2.addWidget(self.threshold_0_color_label)
        self.threshold_0_color_value = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_0_color_value.setMinimumSize(QtCore.QSize(157, 69))
        self.threshold_0_color_value.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_0_color_value.setObjectName("threshold_0_color_value")
        self.horizontalLayout_2.addWidget(self.threshold_0_color_value)
        self.threshold_0_color_box = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_0_color_box.setMinimumSize(QtCore.QSize(157, 69))
        self.threshold_0_color_box.setStyleSheet("background-color: #000000")
        self.threshold_0_color_box.setText("")
        self.threshold_0_color_box.setObjectName("threshold_0_color_box")
        self.horizontalLayout_2.addWidget(self.threshold_0_color_box)
        self.threshold_0_button = QtWidgets.QPushButton(Threshold3DialogBase)
        self.threshold_0_button.setObjectName("threshold_0_button")
        self.horizontalLayout_2.addWidget(self.threshold_0_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.alpha_0_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.alpha_0_label.setTextFormat(QtCore.Qt.PlainText)
        self.alpha_0_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_0_label.setObjectName("alpha_0_label")
        self.horizontalLayout_7.addWidget(self.alpha_0_label)
        self.alpha_0_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.alpha_0_slider.setMaximumSize(QtCore.QSize(331, 17))
        self.alpha_0_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_0_slider.setObjectName("alpha_0_slider")
        self.horizontalLayout_7.addWidget(self.alpha_0_slider)
        self.alpha_0_value = QtWidgets.QLabel(Threshold3DialogBase)
        self.alpha_0_value.setTextFormat(QtCore.Qt.PlainText)
        self.alpha_0_value.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_0_value.setObjectName("alpha_0_value")
        self.horizontalLayout_7.addWidget(self.alpha_0_value)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.threshold_1_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_1_label.setObjectName("threshold_1_label")
        self.horizontalLayout_3.addWidget(self.threshold_1_label)
        self.threshold_1_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.threshold_1_slider.setMaximumSize(QtCore.QSize(390, 21))
        self.threshold_1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_1_slider.setObjectName("threshold_1_slider")
        self.horizontalLayout_3.addWidget(self.threshold_1_slider)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Threshold3DialogBase)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.threshold_1_color_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_1_color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_1_color_label.setObjectName("threshold_1_color_label")
        self.horizontalLayout_4.addWidget(self.threshold_1_color_label)
        self.threshold_1_color_value = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_1_color_value.setMinimumSize(QtCore.QSize(157, 69))
        self.threshold_1_color_value.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_1_color_value.setObjectName("threshold_1_color_value")
        self.horizontalLayout_4.addWidget(self.threshold_1_color_value)
        self.threshold_1_color_box = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_1_color_box.setMinimumSize(QtCore.QSize(157, 69))
        self.threshold_1_color_box.setStyleSheet("background-color: #000000")
        self.threshold_1_color_box.setText("")
        self.threshold_1_color_box.setObjectName("threshold_1_color_box")
        self.horizontalLayout_4.addWidget(self.threshold_1_color_box)
        self.threshold_1_button = QtWidgets.QPushButton(Threshold3DialogBase)
        self.threshold_1_button.setObjectName("threshold_1_button")
        self.horizontalLayout_4.addWidget(self.threshold_1_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.alpha_1_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.alpha_1_label.setTextFormat(QtCore.Qt.PlainText)
        self.alpha_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_1_label.setObjectName("alpha_1_label")
        self.horizontalLayout_8.addWidget(self.alpha_1_label)
        self.alpha_1_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.alpha_1_slider.setMaximumSize(QtCore.QSize(331, 17))
        self.alpha_1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_1_slider.setObjectName("alpha_1_slider")
        self.horizontalLayout_8.addWidget(self.alpha_1_slider)
        self.alpha_1_value = QtWidgets.QLabel(Threshold3DialogBase)
        self.alpha_1_value.setTextFormat(QtCore.Qt.PlainText)
        self.alpha_1_value.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_1_value.setObjectName("alpha_1_value")
        self.horizontalLayout_8.addWidget(self.alpha_1_value)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.threshold_2_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_2_label.setObjectName("threshold_2_label")
        self.horizontalLayout_5.addWidget(self.threshold_2_label)
        self.threshold_2_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.threshold_2_slider.setMaximumSize(QtCore.QSize(390, 21))
        self.threshold_2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.threshold_2_slider.setObjectName("threshold_2_slider")
        self.horizontalLayout_5.addWidget(self.threshold_2_slider)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(Threshold3DialogBase)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.threshold_2_color_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_2_color_label.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_2_color_label.setObjectName("threshold_2_color_label")
        self.horizontalLayout_6.addWidget(self.threshold_2_color_label)
        self.threshold_2_color_value = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_2_color_value.setMinimumSize(QtCore.QSize(157, 69))
        self.threshold_2_color_value.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_2_color_value.setObjectName("threshold_2_color_value")
        self.horizontalLayout_6.addWidget(self.threshold_2_color_value)
        self.threshold_2_color_box = QtWidgets.QLabel(Threshold3DialogBase)
        self.threshold_2_color_box.setMinimumSize(QtCore.QSize(157, 69))
        self.threshold_2_color_box.setStyleSheet("background-color: #000000")
        self.threshold_2_color_box.setText("")
        self.threshold_2_color_box.setObjectName("threshold_2_color_box")
        self.horizontalLayout_6.addWidget(self.threshold_2_color_box)
        self.threshold_2_button = QtWidgets.QPushButton(Threshold3DialogBase)
        self.threshold_2_button.setObjectName("threshold_2_button")
        self.horizontalLayout_6.addWidget(self.threshold_2_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.alpha_2_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.alpha_2_label.setTextFormat(QtCore.Qt.PlainText)
        self.alpha_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_2_label.setObjectName("alpha_2_label")
        self.horizontalLayout_9.addWidget(self.alpha_2_label)
        self.alpha_2_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.alpha_2_slider.setMaximumSize(QtCore.QSize(331, 17))
        self.alpha_2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_2_slider.setObjectName("alpha_2_slider")
        self.horizontalLayout_9.addWidget(self.alpha_2_slider)
        self.alpha_2_value = QtWidgets.QLabel(Threshold3DialogBase)
        self.alpha_2_value.setTextFormat(QtCore.Qt.PlainText)
        self.alpha_2_value.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_2_value.setObjectName("alpha_2_value")
        self.horizontalLayout_9.addWidget(self.alpha_2_value)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.base_label = QtWidgets.QLabel(Threshold3DialogBase)
        self.base_label.setObjectName("base_label")
        self.horizontalLayout_11.addWidget(self.base_label)
        self.base_slider = QtWidgets.QSlider(Threshold3DialogBase)
        self.base_slider.setOrientation(QtCore.Qt.Horizontal)
        self.base_slider.setObjectName("base_slider")
        self.horizontalLayout_11.addWidget(self.base_slider)
        self.doubleSpinBox_b = QtWidgets.QDoubleSpinBox(Threshold3DialogBase)
        self.doubleSpinBox_b.setObjectName("doubleSpinBox_b")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox_b)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.splitter = QtWidgets.QSplitter(Threshold3DialogBase)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.precision_label = QtWidgets.QLabel(self.splitter)
        self.precision_label.setObjectName("precision_label")
        self.precision_spinbox = QtWidgets.QSpinBox(self.splitter)
        self.precision_spinbox.setObjectName("precision_spinbox")
        self.horizontalLayout_10.addWidget(self.splitter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.button_box = QtWidgets.QDialogButtonBox(Threshold3DialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_5.addWidget(self.button_box)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Threshold3DialogBase)
        self.button_box.accepted.connect(Threshold3DialogBase.accept)
        self.button_box.rejected.connect(Threshold3DialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(Threshold3DialogBase)

    def retranslateUi(self, Threshold3DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Threshold3DialogBase.setWindowTitle(_translate("Threshold3DialogBase", "Threshold3"))
        self.threshold_0_label.setText(_translate("Threshold3DialogBase", "T_0"))
        self.threshold_0_color_label.setText(_translate("Threshold3DialogBase", "T_0 color"))
        self.threshold_0_color_value.setText(_translate("Threshold3DialogBase", "(0, 0, 0, 1.0)"))
        self.threshold_0_button.setText(_translate("Threshold3DialogBase", "Change"))
        self.alpha_0_label.setText(_translate("Threshold3DialogBase", "T_0 alpha"))
        self.alpha_0_value.setText(_translate("Threshold3DialogBase", "0"))
        self.threshold_1_label.setText(_translate("Threshold3DialogBase", "T_1"))
        self.threshold_1_color_label.setText(_translate("Threshold3DialogBase", "T_1 color"))
        self.threshold_1_color_value.setText(_translate("Threshold3DialogBase", "(0, 0, 0, 1.0)"))
        self.threshold_1_button.setText(_translate("Threshold3DialogBase", "Change"))
        self.alpha_1_label.setText(_translate("Threshold3DialogBase", "T_1 alpha"))
        self.alpha_1_value.setText(_translate("Threshold3DialogBase", "0"))
        self.threshold_2_label.setText(_translate("Threshold3DialogBase", "T_2"))
        self.threshold_2_color_label.setText(_translate("Threshold3DialogBase", "T_2 color"))
        self.threshold_2_color_value.setText(_translate("Threshold3DialogBase", "(0, 0, 0, 1.0)"))
        self.threshold_2_button.setText(_translate("Threshold3DialogBase", "Change"))
        self.alpha_2_label.setText(_translate("Threshold3DialogBase", "T_2 alpha"))
        self.alpha_2_value.setText(_translate("Threshold3DialogBase", "0"))
        self.base_label.setText(_translate("Threshold3DialogBase", "radius"))
        self.precision_label.setText(_translate("Threshold3DialogBase", "Precision"))

